### PR TITLE
Build with DMD v2.072.2

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
@nemanja-boric-sociomantic can you please enable travis checks for this repo to at least verify it all compiles?

**Comment by nemanja-boric-sociomantic** [comment]
Yes.

**Comment by nemanja-boric-sociomantic** [comment]
Added `.travis.yml` to this PR

**Comment by nemanja-boric-sociomantic** [comment]
Green :-)

**Comment by mihails-strasuns-sociomantic** [comment]
:+1:

**Pull request merged**
